[project]
name = "neural-network-mlp-sample"
version = "0.1.0"
requires-python = ">=3.8"

dependencies = [
    "numpy>=1.21.0",
    "matplotlib>=3.5.0",
    "pandas>=1.3.0",
    "p2j>=1.3.2",
    "ipykernel>=6.29.5",
]


